"""initial migration

Revision ID: 49e15bd78655
Revises: 
Create Date: 2026-07-30 06:59:51.131387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e15bd78655'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tariff_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estimated_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_code'), ['code'], unique=True)

    op.create_table('shipment_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.String(length=150), nullable=False),
    sa.Column('piece', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('total_tariff', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_orders_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_orders_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_orders_status'))
        batch_op.drop_index(batch_op.f('ix_shipment_orders_service_id'))

    op.drop_table('shipment_orders')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_code'))

    op.drop_table('services')
    # ### end Alembic commands ###
